plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
Title: Josianne Lachapelle
Description: Welcome to my personal webpage! I am a postdoctoral research fellow in experimental genomics at the University of Toronto Mississauga.
url: josiannelachapelle.github.io
